[theme]
#for interractive elemement
primaryColor = "#008080" #dark teal

#for main content area
#all background
backgroundColor = "#DCDCDC" #gray

#for sidebar background
sidebarBackgroundColor  = "#00CD00" #green

#for text
textColor = "#000000" #black

#font
font = "sans serif"